/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/src/Breadcrumb.vue')['default']
    ConfigGlobal: typeof import('./src/components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentWrap: typeof import('./src/components/ContentWrap/src/ContentWrap.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/src/ContextMenu.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/src/DynamicForm.vue')['default']
    DynamicFormItems: typeof import('./src/components/DynamicForm/src/DynamicFormItems.vue')['default']
    Error: typeof import('./src/components/Error/src/Error.vue')['default']
    Header: typeof import('./src/components/Header/src/Header.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    Layout: typeof import('./src/components/Layout/src/Layout.vue')['default']
    Menu: typeof import('./src/components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/src/MenuItem.vue')['default']
    Modal: typeof import('./src/components/Modal/src/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TagsView: typeof import('./src/components/TagsView/src/TagsView.vue')['default']
  }
}
