/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../components/Breadcrumb/src/Breadcrumb.vue')['default']
    ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentWrap: typeof import('./../components/ContentWrap/src/ContentWrap.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu/src/ContextMenu.vue')['default']
    DynamicForm: typeof import('./../components/DynamicForm/src/DynamicForm.vue')['default']
    DynamicFormItems: typeof import('./../components/DynamicForm/src/DynamicFormItems.vue')['default']
    Error: typeof import('./../components/Error/src/Error.vue')['default']
    Header: typeof import('./../components/Header/src/Header.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    InputPrepend: typeof import('./../components/InputPrepend.vue')['default']
    Layout: typeof import('./../components/Layout/src/Layout.vue')['default']
    Menu: typeof import('./../components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./../components/Menu/src/MenuItem.vue')['default']
    Modal: typeof import('./../components/Modal/src/Modal.vue')['default']
    ModalFooter: typeof import('./../components/ModalFooter/src/ModalFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./../components/Table/src/Table.vue')['default']
    TagsView: typeof import('./../components/TagsView/src/TagsView.vue')['default']
    TreeSelector: typeof import('./../components/TreeSelector/src/TreeSelector.vue')['default']
    Verify: typeof import('./../components/Verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./../components/Verifition/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./../components/Verifition/Verify/VerifySlide.vue')['default']
  }
}
